FROM mcr.microsoft.com/playwright:v1.47.2-focal

ARG MODULE_PATH

WORKDIR /workspace

COPY $MODULE_PATH /workspace
COPY requirements.txt /workspace

# playwright doesn't have python and pip installed by default
# make python3 the default python
RUN apt-get update && apt-get install -y python3 python3-pip && \
    ln -s /usr/bin/python3 /usr/bin/python
RUN pip install -r requirements.txt && pip install --no-cache-dir .